include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  strong-mode:
    implicit-dynamic: true
  errors:
    prefer_double_quotes: ignore
    prefer_expression_function_bodies: ignore